{
 "title": "Fulfilment",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "90th Percentile Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum without(instance, job, tier)(rate(fulfilment_processing_seconds_bucket[5m])))",
     "legendFormat": "{{instance_number}}"
    }
   ]
  },
  {
   "title": "Average Processing Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "avg by(le) (rate(fulfilment_processing_seconds_bucket[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(instance, job) (rate(process_cpu_seconds_total{job=\"processor\"}[5m]))",
     "legendFormat": "i: {{instance_number}}"
    }
   ]
  },
  {
   "title": ".NET Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "i: {{instance_number}}" }
   ]
  }
 ]
}