#!/bin/bash
mysql -h${MYSQL_HOST} -u${MYSQL_USER} -p${MYSQL_PASSWORD} << EOF
CREATE DATABASE IF NOT EXISTS Universe;
USE Universe;
CREATE TABLE IF NOT EXISTS Heroes (
 HeroId INT NOT NULL AUTO_INCREMENT,
 HeroName VARCHAR(255) NOT NULL,
 PRIMARY KEY (HeroId));
INSERT INTO Heroes(HeroId, HeroName) VALUES(1, "IRON MAN");
INSERT INTO Heroes(HeroId, HeroName) VALUES(2, "SPIDER MAN");
INSERT INTO Heroes(HeroId, HeroName) VALUES(3, "CAPTAIN AMERICA");
EOF